$schema: "https://json-schema.org/draft/2020-12/schema"
description: "Schema for user-provided configuration files."
type: object
additionalProperties: false
properties:
  dummy_text:
    description: A template example. Should be deleted in real applications.
    type: string
  techs:
    description: "A dictionary of technology configurations."
    type: object
    additionalProperties:
      type: object
      properties:
        density:
          type: number
          description: "Density of renewable technology in MW/km2."
        lifetime:
          type: number
        costs:
          type: object
          properties:
            CAPEX:
              type: number
              description: "Upfront cost in EUR/MW."
            OPEX:
              type: number
              description: "Fixed operational cost in EUR/MW."
            WACC:
              type: number
              description: "Weighted average cost of capital."
          required: ["CAPEX", "OPEX", "WACC"]
          additionalProperties: false
