# A minimal example of how to configure this module

techs:
  pv_rooftop:
    density: 50
    lifetime: 40
    costs:
      CAPEX: 705000
      OPEX: 9800
      WACC: 0.05

  pv_open_field:
    density: 45
    lifetime: 40
    costs:
      CAPEX: 380000
      OPEX: 9500
      WACC: 0.04
  
  wind_onshore:
    density: 5
    lifetime: 30
    costs: # TODO: this needs to be country-specific
      CAPEX: 1146644
      OPEX: 16663
      WACC: 0.04
  
  wind_offshore:
    density: 5
    lifetime: 30
    costs: # TODO: this needs to be country-specific
      CAPEX: 2248224
      OPEX: 32000
      WACC: 0.05
    